# Generated by Django 5.2.7 on 2025-10-24 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serieepisodio',
            options={'ordering': ['temporada', 'episodio']},
        ),
        migrations.RemoveField(
            model_name='serieepisodio',
            name='serie',
        ),
        migrations.AddField(
            model_name='temporada',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.serie'),
        ),
        migrations.AlterField(
            model_name='continente',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='diretor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filmes', to='app.diretor'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='duracao',
            field=models.PositiveIntegerField(help_text='Duração em minutos'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filmes', to='app.genero'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filmes', to='app.pais'),
        ),
        migrations.AlterField(
            model_name='filmeator',
            name='ator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmes', to='app.ator'),
        ),
        migrations.AlterField(
            model_name='filmeator',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atores', to='app.filme'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='continente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paises', to='app.continente'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='diretor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='app.diretor'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='duracao',
            field=models.PositiveIntegerField(help_text='Duração média dos episódios (min)'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='app.genero'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='app.pais'),
        ),
        migrations.AlterField(
            model_name='serieepisodio',
            name='duracao',
            field=models.PositiveIntegerField(help_text='Duração em minutos'),
        ),
        migrations.AlterField(
            model_name='serieepisodio',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='app.temporada'),
        ),
    ]
