# Generated by Django 5.2.7 on 2025-10-27 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_serieepisodio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serieepisodio',
            options={},
        ),
        migrations.AddField(
            model_name='serieepisodio',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='app.serie'),
        ),
        migrations.AlterField(
            model_name='serieepisodio',
            name='duracao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serieepisodio',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.temporada'),
        ),
    ]
